### ISSUE TITLE
class rename destructor issue

### ISSUE THREAD

**Issue by pdavydov108** [lyuts/vim-rtags#32] opened 2016-03-24 11:51 UTC
Hello @lyuts , I've noticed a weird issue with rename. When I try to change a class name with <leader>rw, and then type 'a' to rename it everywhere, destructor is not renamed correctly. I'm not sure if it's an issue with plugin or with rtags itself, but instead of renaming virtual ~MyClass() = default; to virtual ~NewName() = default; it produces virtual NewNameMyClass() = default;. All other symbols are renamed correctly.

**Comment by asenac** [comment] 2016-03-31 21:02
The location returned with "rc -e --rename -r" for destructors points to the ~ character. I guess this is not a bug in RTags as Rtags' emacs plugin takes this into account when renaming https://github.com/Andersbakken/rtags/blob/master/src/rtags.el#L2275. I guess vim-rtags should do the same.

**Comment by pdavydov108** [comment] 2016-04-01 07:30
@asenac Thanks for fixing it! I thought that the issue might be with location pointing to '~', but had no time to check it. Again, thanks, this fix will make my daily job easier!

**Comment by lyuts** [comment] 2016-04-02 04:57
Pull request from @asenac has been merged. Closing this issue.

**Closed by lyuts** 2016-04-02 04:57 UTC
